name: SonarCloud Analysis
on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # For Sonar incremental analysis

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Install SonarScanner
        shell: powershell
        run: |
          if (-not (Test-Path .\.sonar\scanner)) {
            New-Item -Path .\.sonar\scanner -ItemType Directory
            dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner
          }

      - name: Restore NuGet Packages
        shell: powershell
        run: nuget restore encrypt/FileEncryptor.csproj  # Targets the actual project file

      - name: Sonar Begin
        shell: powershell
        run: |
          .\.sonar\scanner\dotnet-sonarscanner begin /k:"arthurpanhku_SecurityCookie" /o:"k1l2m3n4o5p6q7r8s9t0" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml  # Add coverage if needed

      - name: Build Project
        shell: powershell
        run: msbuild encrypt/FileEncryptor.csproj /t:Rebuild /p:Configuration=Release

      - name: Sonar End
        shell: powershell
        run: |
          .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
